// The local stack as data — the pure half of `scripts/setup-local.mjs` and
// `scripts/dev-local.mjs`. Everything here is a string or a decision; the
// scripts own the processes, sockets and files.
//
// Why these exist at all: a fresh clone used to need an Upstash account, a
// hand-assembled `.env.local`, a tenant uuid looked up in Studio, and the
// knowledge that four processes start in a fixed order. Each of those is now a
// value or a check in this module, so the two scripts stay thin and the rules
// are unit-tested (`__tests__/local-stack.test.ts`).

import { createHash } from "node:crypto";
import { join } from "node:path";

export const LOCAL_APP_URL = "http://127.0.0.1:3000";
export const LOCAL_INNGEST_URL = "http://127.0.0.1:8288";

/** The Upstash-compatible REST front for the local Redis that
 *  `infra/local/docker-compose.yml` runs. Loopback-bound; the token is a fixed,
 *  published, local-only value — the same posture as Supabase's well-known
 *  local keys. A test pins the compose file to these two constants. */
export const LOCAL_REDIS_REST_URL = "http://127.0.0.1:8079";
export const LOCAL_REDIS_REST_TOKEN = "devpilot-local-dev-token";

// ── Inngest: the DURABLE local server, not the dev server ───────────────────
//
// `inngest dev` keeps the queue and every in-flight run IN MEMORY; `--persist`
// was measured to keep only the history (a sleeping run came back after a
// restart as "Running" with no job behind it, forever). `inngest start` is the
// self-hosted server: queue + run state in Redis (the compose one, db 1, on
// its own loopback port), history in SQLite, and it needs an event key and a
// signing key - both generated by `setup:local`. The SDK picks that server
// only when `INNGEST_DEV` is EXPLICITLY `0` (unset under `next dev` infers
// the dev server), so that value is written too.

export const LOCAL_INNGEST_REDIS_URI = "redis://127.0.0.1:16379/1";
// 127.0.0.1, not localhost: `dev:local` binds the app to IPv4 loopback only
// (so instant sign-in is never reachable from the Wi-Fi), and `localhost` may
// resolve to ::1 first.
export const INNGEST_SDK_URL = "http://127.0.0.1:3000/api/inngest";

export type InngestMode = "server" | "dev";

/** `server` only when the env says so explicitly AND both keys are present;
 *  anything else is the keyless dev server (what a hand-written `.env.local`
 *  from before durable mode has). */
export function inngestModeFor(env: Record<string, string | undefined>): InngestMode {
  const dev = (env.INNGEST_DEV ?? "").trim().toLowerCase();
  const explicitCloud = dev === "0" || dev === "false";
  const keys = (env.INNGEST_EVENT_KEY ?? "").trim() && (env.INNGEST_SIGNING_KEY ?? "").trim();
  return explicitCloud && keys ? "server" : "dev";
}

/** The SDK accepts `signkey-<env>-<hex>` and hashes the hex; the server wants
 *  the hex alone ("must be hex string with even number of chars"). */
export function stripSigningKeyPrefix(key: string): string {
  return key.trim().replace(/^signkey-[\w]+-/, "");
}

/** argv + child env for `inngest start`. Keys go through the ENVIRONMENT, which
 *  the server reads (verified: it boots with INNGEST_EVENT_KEY/INNGEST_SIGNING_KEY
 *  set and no flags, and refuses with "signing-key is required" without), so
 *  they never appear in `ps`. */
export function inngestServerSpec(
  env: Record<string, string | undefined>,
  opts: { dataDir: string; sdkUrl?: string; redisUri?: string },
): { args: string[]; env: Record<string, string> } {
  return {
    args: [
      "start",
      "-u",
      opts.sdkUrl ?? INNGEST_SDK_URL,
      "--sqlite-dir",
      opts.dataDir,
      "--redis-uri",
      opts.redisUri ?? LOCAL_INNGEST_REDIS_URI,
      "--poll-interval",
      "5",
    ],
    env: {
      INNGEST_EVENT_KEY: (env.INNGEST_EVENT_KEY ?? "").trim(),
      INNGEST_SIGNING_KEY: stripSigningKeyPrefix(env.INNGEST_SIGNING_KEY ?? ""),
    },
  };
}

/** What `.env.local` must carry for all four processes to come up. The order
 *  is the order the setup report prints them in. */
export const REQUIRED_LOCAL_ENV_KEYS = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  "SUPABASE_SECRET_KEY",
  "DATABASE_URL",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "DEVPILOT_RUNNER_REGISTRATION_KEY",
  "DEVPILOT_RUNNER_TENANT_ID",
  "SECRETS_ENCRYPTION_KEY",
  "INNGEST_DEV",
  "INNGEST_BASE_URL",
  "INNGEST_EVENT_KEY",
  "INNGEST_SIGNING_KEY",
  "NEXT_PUBLIC_APP_URL",
  "LOCAL_CC_ENGINE_URL",
] as const;

export type RequiredLocalEnvKey = (typeof REQUIRED_LOCAL_ENV_KEYS)[number];

/** The keys the dev-server mode does NOT need - a `.env.local` written before
 *  durable mode (`INNGEST_DEV=1`, no keys) is still a complete dev-mode file. */
const SERVER_MODE_ONLY_KEYS: ReadonlySet<string> = new Set([
  "INNGEST_BASE_URL",
  "INNGEST_EVENT_KEY",
  "INNGEST_SIGNING_KEY",
]);

export function requiredLocalEnvKeysFor(mode: InngestMode): readonly string[] {
  return mode === "server"
    ? REQUIRED_LOCAL_ENV_KEYS
    : REQUIRED_LOCAL_ENV_KEYS.filter((k) => !SERVER_MODE_ONLY_KEYS.has(k));
}

// ── `supabase status -o json` ───────────────────────────────────────────────

/** The CLI prints WARN lines and an upgrade nag to stderr, and on some
 *  versions a `Stopped services: […]` line to stdout before the object. Take
 *  the outermost `{…}` rather than trusting the whole stream to be JSON. */
export function parseSupabaseStatus(stdout: string): Record<string, string> {
  const start = stdout.indexOf("{");
  const end = stdout.lastIndexOf("}");
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      "supabase status printed no JSON object — is the local stack running? (`supabase start`)",
    );
  }
  const parsed: unknown = JSON.parse(stdout.slice(start, end + 1));
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("supabase status printed something other than an object");
  }
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(parsed as Record<string, unknown>)) {
    if (typeof v === "string") out[k] = v;
  }
  return out;
}

export type SupabaseLocalEnv = {
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: string;
  SUPABASE_SECRET_KEY: string;
  DATABASE_URL: string;
  /** Where local sign-in mail lands (Mailpit). Blank outside local dev. */
  NEXT_PUBLIC_LOCAL_MAIL_URL: string;
};

/** Map the status object onto the env keys the app reads. Refuses an older
 *  CLI that only reports the legacy JWT keys (`ANON_KEY`/`SERVICE_ROLE_KEY`):
 *  the app is written against `sb_publishable_…`/`sb_secret_…` and a JWT in
 *  those slots fails later, far from here, as a bare auth error. */
export function supabaseStatusToEnv(status: Record<string, string>): SupabaseLocalEnv {
  const apiUrl = (status.API_URL ?? "").trim();
  const publishableKey = (status.PUBLISHABLE_KEY ?? "").trim();
  const secretKey = (status.SECRET_KEY ?? "").trim();
  const dbUrl = (status.DB_URL ?? "").trim();
  const missing = (
    [
      ["API_URL", apiUrl],
      ["PUBLISHABLE_KEY", publishableKey],
      ["SECRET_KEY", secretKey],
      ["DB_URL", dbUrl],
    ] as const
  )
    .filter(([, v]) => v.length === 0)
    .map(([k]) => k);
  if (missing.length > 0) {
    throw new Error(
      `supabase status did not report ${missing.join(", ")} (got: ${Object.keys(status).join(", ") || "nothing"}). ` +
        "Upgrade the Supabase CLI (brew upgrade supabase) — the app needs the sb_publishable_/sb_secret_ key format.",
    );
  }
  if (!publishableKey.startsWith("sb_publishable_")) {
    throw new Error(
      `PUBLISHABLE_KEY does not look like an sb_publishable_ key (starts with "${publishableKey.slice(0, 12)}…")`,
    );
  }
  if (!secretKey.startsWith("sb_secret_")) {
    throw new Error("SECRET_KEY does not look like an sb_secret_ key");
  }
  return {
    NEXT_PUBLIC_SUPABASE_URL: apiUrl,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: publishableKey,
    SUPABASE_SECRET_KEY: secretKey,
    DATABASE_URL: dbUrl,
    NEXT_PUBLIC_LOCAL_MAIL_URL: status.MAILPIT_URL ?? status.INBUCKET_URL ?? "",
  };
}

/** The URLs the scripts print once everything is up. */
export function localStackUrls(status: Record<string, string>): {
  app: string;
  inngest: string;
  studio: string;
  mailpit: string;
} {
  return {
    app: LOCAL_APP_URL,
    inngest: LOCAL_INNGEST_URL,
    studio: status.STUDIO_URL ?? "",
    mailpit: status.MAILPIT_URL ?? status.INBUCKET_URL ?? "",
  };
}

// ── Secrets + the assembled value set ───────────────────────────────────────

export type LocalSecrets = {
  DEVPILOT_RUNNER_REGISTRATION_KEY: string;
  SECRETS_ENCRYPTION_KEY: string;
  INNGEST_EVENT_KEY: string;
  INNGEST_SIGNING_KEY: string;
};

/** Every value is chosen so `serializeEnvValue` never has to quote or refuse
 *  it: hex for the runner and Inngest keys (the Inngest server insists on hex
 *  for the signing key; the SDK form carries the `signkey-prod-` prefix it
 *  strips before hashing), and for the encryption key the exact shape
 *  `validateEncryptionKey` checks (32 random bytes, base64). */
export function generateLocalSecrets(random: (bytes: number) => Buffer): LocalSecrets {
  return {
    DEVPILOT_RUNNER_REGISTRATION_KEY: random(32).toString("hex"),
    SECRETS_ENCRYPTION_KEY: random(32).toString("base64"),
    INNGEST_EVENT_KEY: random(32).toString("hex"),
    INNGEST_SIGNING_KEY: `signkey-prod-${random(32).toString("hex")}`,
  };
}

/** Everything `setup:local` offers to `fillEnvTemplate`. The tenant id is
 *  included only when the account bootstrap produced one — a blank entry would
 *  "set" a blank, which reads as configured and is not. */
export function buildLocalEnvValues(input: {
  supabase: SupabaseLocalEnv;
  secrets: LocalSecrets;
  tenantId?: string;
  /** From `runnerNameFor(os.hostname())`; omitted by callers that have no host. */
  runnerName?: string;
}): Record<string, string> {
  const values: Record<string, string> = {
    NEXT_PUBLIC_SUPABASE_URL: input.supabase.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: input.supabase.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    SUPABASE_SECRET_KEY: input.supabase.SUPABASE_SECRET_KEY,
    DATABASE_URL: input.supabase.DATABASE_URL,
    UPSTASH_REDIS_REST_URL: LOCAL_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: LOCAL_REDIS_REST_TOKEN,
    DEVPILOT_RUNNER_REGISTRATION_KEY: input.secrets.DEVPILOT_RUNNER_REGISTRATION_KEY,
    SECRETS_ENCRYPTION_KEY: input.secrets.SECRETS_ENCRYPTION_KEY,
    // Durable mode: explicit cloud routing at the LOCAL self-hosted server.
    INNGEST_DEV: "0",
    INNGEST_BASE_URL: LOCAL_INNGEST_URL,
    INNGEST_EVENT_KEY: input.secrets.INNGEST_EVENT_KEY,
    INNGEST_SIGNING_KEY: input.secrets.INNGEST_SIGNING_KEY,
    NEXT_PUBLIC_APP_URL: LOCAL_APP_URL,
    LOCAL_CC_ENGINE_URL: LOCAL_APP_URL,
    // Instant sign-in: the magic link only ever lands in Mailpit on this
    // machine, so the login page signs the visitor in directly instead.
    // Doubly gated on a loopback Supabase URL (lib/auth/local-signin.ts).
    DEVPILOT_LOCAL_PASSWORDLESS: "1",
  };
  if (input.supabase.NEXT_PUBLIC_LOCAL_MAIL_URL) {
    values.NEXT_PUBLIC_LOCAL_MAIL_URL = input.supabase.NEXT_PUBLIC_LOCAL_MAIL_URL;
  }
  if (input.tenantId) values.DEVPILOT_RUNNER_TENANT_ID = input.tenantId;
  if (input.runnerName) values.DEVPILOT_RUNNER_NAME = input.runnerName;
  return values;
}

// ── Preflight predicates ────────────────────────────────────────────────────

/** True only for a loopback host — the one case where `dev:local` may answer
 *  "Redis is down" by starting the compose stack. A real Upstash URL is never
 *  "fixed" with Docker. Hostname comparison, never a prefix match. */
export function isLocalRedisUrl(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    return host === "127.0.0.1" || host === "localhost" || host === "[::1]" || host === "::1";
  } catch {
    return false;
  }
}

/** The Upstash REST `GET /ping` answer, as the app's own `validateRedis` reads it. */
export function isPong(body: unknown): boolean {
  return !!body && typeof body === "object" && (body as { result?: unknown }).result === "PONG";
}

export type ClaudeAuthState = "logged-in" | "logged-out" | "unknown";

export type SupabaseContainerState = "absent" | "running" | "stopped";

/** What to do when the Supabase API is not answering, given what Docker says
 *  about the database container. The reboot race this encodes: Docker Desktop
 *  auto-restarts the containers on its own after a reboot or an engine
 *  restart, and `supabase start` run into a database that is still booting
 *  fails with "container is not ready: starting" - which is not a failure to
 *  act on, it is a reason to wait. */
export function decideSupabaseBringUp(state: SupabaseContainerState): "start" | "wait-then-start" {
  return state === "running" ? "wait-then-start" : "start";
}

/** Map `docker ps -a --format {{.Status}}` for the db container (or "" when
 *  there is none) onto the three states above. */
export function classifySupabaseContainer(status: string | null): SupabaseContainerState {
  if (status === null || status.trim() === "") return "absent";
  return /^Up\b/i.test(status.trim()) ? "running" : "stopped";
}

/** `claude auth status` prints a JSON object with `loggedIn`. Anything else —
 *  an older CLI, a crash, no output — is `unknown`, which the scripts report as
 *  a warning rather than a verdict. */
export function classifyClaudeAuth(stdout: string): ClaudeAuthState {
  const start = stdout.indexOf("{");
  const end = stdout.lastIndexOf("}");
  if (start === -1 || end === -1 || end < start) return "unknown";
  try {
    const parsed: unknown = JSON.parse(stdout.slice(start, end + 1));
    const loggedIn = (parsed as { loggedIn?: unknown })?.loggedIn;
    if (loggedIn === true) return "logged-in";
    if (loggedIn === false) return "logged-out";
    return "unknown";
  } catch {
    return "unknown";
  }
}

/** Major version out of `process.versions.node` (`"24.13.0"` → 24). */
export function nodeMajor(version: string): number {
  const n = Number.parseInt(version.split(".")[0] ?? "", 10);
  return Number.isFinite(n) ? n : 0;
}

export const MIN_NODE_MAJOR = 20;

// ── What survives a restart ─────────────────────────────────────────────────
//
// The database (Supabase volumes), the queue (the compose volume), the
// workspaces (WORKSPACE_ROOT, outside the repo) and - once `dev-inngest.mjs`
// runs the dev server with `--persist` - every in-flight durable run all
// outlive a restart on their own. The three things below are the ones that
// did NOT, and each is a small rule rather than a mechanism.

/** A stable runner name, so every start re-registers the SAME `runners` row
 *  (the register route upserts on `tenant_id,name`) instead of minting
 *  `local-cc-darwin-<pid>` per start and leaving a trail of offline rows for
 *  the watchdog to sweep. */
export function runnerNameFor(hostname: string): string {
  const slug = hostname
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  return slug.length > 0 ? `local-cc-${slug}` : "local-cc-local";
}

/** Where `setup:local` keeps a copy of `.env.local`, OUTSIDE the repo. The file
 *  is gitignored, and a `git clean -fdx` (or a re-clone into the same place)
 *  takes it with it - including `SECRETS_ENCRYPTION_KEY`, without which every
 *  secret already stored in the local database is unreadable forever. Keyed on
 *  the repo path so two clones do not share one backup. */
export function envBackupPath(home: string, repoDir: string): string {
  const key = createHash("sha256").update(repoDir).digest("hex").slice(0, 12);
  return join(home, ".devpilot", "env-backups", `${key}.env.local`);
}

/** `pnpm install` has not been run since the lockfile last changed (or at all).
 *  pnpm stamps `node_modules/.modules.yaml` on every install, so its mtime is
 *  the install time. A warning, not a gate - a developer mid-edit knows. */
export function isInstallStale(lockMtimeMs: number | null, modulesMtimeMs: number | null): boolean {
  if (lockMtimeMs === null) return false;
  if (modulesMtimeMs === null) return true;
  return lockMtimeMs > modulesMtimeMs;
}

// ── GitHub OAuth (the one credential a clone cannot generate) ───────────────
//
// Every project is a GitHub repo (both New-project flows need a token), and
// the token comes from Supabase Auth's GitHub provider - which on a LOCAL
// Supabase means the operator's OWN OAuth App, with the local GoTrue as its
// callback. `supabase/config.toml` enables the provider and reads the two
// values from `supabase/.env` (which the CLI loads), so the app can be
// registered once and the values pasted into `setup:local`.

export const SUPABASE_DOTENV_GITHUB_KEYS = [
  "SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID",
  "SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET",
] as const;

export type GithubOAuthApp = { clientId: string; clientSecret: string };

/** The two lines GoTrue reads (via config.toml's `env()`), for `supabase/.env`. */
export function buildSupabaseDotenvValues(app: GithubOAuthApp): Record<string, string> {
  return {
    SUPABASE_AUTH_EXTERNAL_GITHUB_CLIENT_ID: app.clientId.trim(),
    SUPABASE_AUTH_EXTERNAL_GITHUB_SECRET: app.clientSecret.trim(),
  };
}

/** The same app, for the web app's own refresh-token path (`.env.local`). */
export function buildGithubEnvValues(app: GithubOAuthApp): Record<string, string> {
  return {
    GITHUB_OAUTH_CLIENT_ID: app.clientId.trim(),
    GITHUB_OAUTH_CLIENT_SECRET: app.clientSecret.trim(),
  };
}

/** The callback GitHub must be told about: the LOCAL GoTrue, not the app. */
export function githubCallbackUrl(supabaseApiUrl: string): string {
  return `${supabaseApiUrl.replace(/\/+$/, "")}/auth/v1/callback`;
}

/** Printed by setup when no GitHub app is configured yet - the exact fields,
 *  because a wrong callback URL fails at the end of the dance with GitHub's
 *  generic "redirect_uri mismatch". */
export function githubOauthHowto(supabaseApiUrl: string, appUrl: string): string[] {
  return [
    "To connect repos (every project is a GitHub repo), register a GitHub OAuth App once:",
    "  https://github.com/settings/developers → OAuth Apps → New OAuth App",
    `    Homepage URL:               ${appUrl}`,
    `    Authorization callback URL: ${githubCallbackUrl(supabaseApiUrl)}`,
    "  then: pnpm setup:local --github-client-id <id> --github-client-secret <secret>",
    "  (writes supabase/.env + .env.local and restarts the local Supabase so GoTrue picks it up)",
  ];
}
