-- =============================================================================
-- Migration : 20260603030000_m6_acceptance_strategy.sql
-- Phase     : Phase 1 / M6 — parallel workflows (fan-out + fan-in).
-- Purpose   : Wire the data model for parallel sibling runs on a single ticket.
--             Adds:
--               1. tickets.acceptance_strategy  — 'single' | 'all' | 'quorum(n)'
--                  default 'single' keeps Phase 0 behavior untouched.
--               2. tickets.fan_out_group        — uuid identifying a sibling
--                  cohort. Same uuid is stamped onto each sibling run row so
--                  the aggregator can join on (tenant_id, fan_out_group).
--               3. runs.fan_out_group           — uuid; non-null on sibling runs.
--               4. runs.fan_out_role            — text; which sibling slot
--                  (e.g. 'engineer', 'security') this run is filling.
--                  Used by the aggregator to detect duplicates within a cohort.
--               5. fan_in_decisions             — idempotency ledger. One row
--                  per (fan_out_group, phase) records "we already decided".
--                  The aggregator inserts here BEFORE re-emitting the fan-in
--                  dispatch — a 23505 means another invocation got there
--                  first, abort. This is the explicit guard against the
--                  2026-06-02 runaway shape: the aggregator never emits a
--                  dispatch without proving it owns the decision row.
--
-- Design notes
-- ────────────
-- • acceptance_strategy is stored as text (not an enum) so 'quorum(n)' can
--   carry the threshold inline. Validation happens app-side via a parser.
-- • fan_out_group is uuid not text — generated by the dispatcher at fan-out
--   time, stamped onto both the ticket row and each sibling run row.
-- • RLS on fan_in_decisions follows the dispatch_queue pattern: tenant
--   members read-only, all writes denied (service_role bypasses RLS).
-- • Indexes are plain CREATE INDEX (not CONCURRENTLY) — the tables either
--   don't exist yet (fan_in_decisions) or carry sparse data (the two new
--   uuid cols are NULL on every existing row). One-shot transactional
--   migration is safe.
--
-- Execution notes
-- ───────────────
-- Single transaction. Apply via `supabase db push` against the operator's
-- project. Existing tickets get fan_out_group=NULL and acceptance_strategy
-- default='single' — Phase 0 / Phase 1 M0–M5 tickets keep their current
-- single-emit behavior unconditionally.
-- =============================================================================
begin;

-- ---------------------------------------------------------------------------
-- 1.1  tickets: acceptance_strategy + fan_out_group
-- ---------------------------------------------------------------------------
alter table public.tickets
  add column if not exists acceptance_strategy text not null default 'single',
  add column if not exists fan_out_group       uuid;

-- Allow only the known strategy shapes. Anything else trips a CHECK at
-- INSERT/UPDATE time — protects the aggregator from parsing garbage.
-- Drop-and-recreate so the migration is idempotent across re-runs.
alter table public.tickets
  drop constraint if exists tickets_acceptance_strategy_chk;
alter table public.tickets
  add constraint tickets_acceptance_strategy_chk
    check (
      acceptance_strategy = 'single'
      or acceptance_strategy = 'all'
      or acceptance_strategy ~ '^quorum\([0-9]+\)$'
    );

-- Index for the fan-in lookup hot path ("all sibling runs for this cohort").
create index if not exists tickets_fan_out_group_idx
  on public.tickets(tenant_id, fan_out_group)
  where fan_out_group is not null;

-- ---------------------------------------------------------------------------
-- 1.2  runs: fan_out_group + fan_out_role
-- ---------------------------------------------------------------------------
alter table public.runs
  add column if not exists fan_out_group uuid,
  add column if not exists fan_out_role  text;

-- Index — the aggregator's hot path is "all runs for this cohort", scoped
-- by tenant for RLS safety. Partial index keeps it cheap.
create index if not exists runs_fan_out_group_idx
  on public.runs(tenant_id, fan_out_group)
  where fan_out_group is not null;

-- ---------------------------------------------------------------------------
-- 1.3  fan_in_decisions — idempotency ledger
-- ---------------------------------------------------------------------------
-- One row per (fan_out_group, phase). The aggregator INSERTs here BEFORE
-- re-emitting any dispatch. A 23505 unique_violation = another aggregator
-- invocation already owns this decision, so we abort silently.
--
-- The `phase` column lets one cohort be re-used for sequential fan-out steps
-- in the future (Phase 2). Today it's always 'review' for the canonical demo.
create table if not exists public.fan_in_decisions (
  id              uuid         not null default gen_random_uuid()
                    primary key,
  tenant_id       uuid         not null
                    references public.tenants(id) on delete cascade,
  ticket_id       uuid         not null
                    references public.tickets(id) on delete cascade,
  fan_out_group   uuid         not null,
  phase           text         not null default 'review',
  -- Acceptance strategy this decision was evaluated against, snapshotted at
  -- decision time. Lets us audit "what did we promise" without re-reading
  -- the ticket row (which may have moved on by then).
  strategy        text         not null,
  -- Outcome — what the aggregator did with the cohort.
  --   accepted    — strategy satisfied; ticket transitioned.
  --   rejected    — all siblings reported failure (or quorum couldn't be met).
  --   cancelled   — ticket reached terminal state before strategy was satisfied.
  outcome         text         not null
                    check (outcome in ('accepted', 'rejected', 'cancelled')),
  -- Snapshot of sibling run ids that triggered the decision. Cheap audit.
  sibling_runs    jsonb        not null default '[]'::jsonb,
  decided_at      timestamptz  not null default now(),
  decided_by_run  uuid,        -- id of the agent run that closed the decision
  notes           text,

  -- The idempotency anchor. One decision per cohort+phase, period.
  constraint fan_in_decisions_unique_cohort_phase
    unique (fan_out_group, phase),

  constraint fan_in_decisions_sibling_runs_array
    check (jsonb_typeof(sibling_runs) = 'array')
);

comment on table public.fan_in_decisions is
  'Idempotency ledger for fan-in aggregations. The aggregator inserts here '
  'BEFORE re-emitting a dispatch event so the same cohort can never trigger '
  'two transitions. Unique (fan_out_group, phase) is the runaway-shape guard.';

create index if not exists fan_in_decisions_tenant_idx
  on public.fan_in_decisions(tenant_id, decided_at desc);
create index if not exists fan_in_decisions_ticket_idx
  on public.fan_in_decisions(ticket_id);

-- ---------------------------------------------------------------------------
-- 1.4  Row-Level Security on fan_in_decisions
-- Same pattern as dispatch_queue: tenant members read-only, service_role
-- bypasses RLS for all writes (Inngest functions run with service_role).
-- ---------------------------------------------------------------------------
alter table public.fan_in_decisions enable row level security;

create policy fan_in_decisions_member_read
  on public.fan_in_decisions
  for select
  using (tenant_id in (select public.current_user_tenants()));

create policy fan_in_decisions_insert_deny
  on public.fan_in_decisions
  for insert
  with check (false);

create policy fan_in_decisions_update_deny
  on public.fan_in_decisions
  for update
  using (false);

create policy fan_in_decisions_delete_deny
  on public.fan_in_decisions
  for delete
  using (false);

-- ---------------------------------------------------------------------------
-- 1.5  Materialize the Security agent row per tenant.
-- Extends `materialize_builtin_agents` so future tenants get the row at
-- creation time; then runs the materializer for every existing tenant so the
-- security sibling has a real agents.id to thread into runs.agent_id.
-- ---------------------------------------------------------------------------
create or replace function public.materialize_builtin_agents(p_tenant_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_roles jsonb := jsonb_build_array(
    jsonb_build_object('role', 'pm',         'name', 'PM',            'model_tier', 'default'),
    jsonb_build_object('role', 'engineer',   'name', 'Engineer',      'model_tier', 'default'),
    jsonb_build_object('role', 'qa',         'name', 'QA',            'model_tier', 'default'),
    jsonb_build_object('role', 'devops',     'name', 'DevOps',        'model_tier', 'default'),
    jsonb_build_object('role', 'techwriter', 'name', 'Tech Writer',   'model_tier', 'default'),
    jsonb_build_object('role', 'designer',   'name', 'Designer',      'model_tier', 'default'),
    jsonb_build_object('role', 'dataeng',    'name', 'Data Engineer', 'model_tier', 'heavy'),
    jsonb_build_object('role', 'security',   'name', 'Security',      'model_tier', 'default')
  );
  v_row jsonb;
begin
  for v_row in select * from jsonb_array_elements(v_roles)
  loop
    insert into public.agents (tenant_id, name, role, config)
    select p_tenant_id,
           v_row->>'name',
           v_row->>'role',
           jsonb_build_object(
             'wip_limit', 3,
             'assignment_mode', 'push',
             'runner_policy', 'local-cc',
             'model_tier', v_row->>'model_tier'
           )
    where not exists (
      select 1 from public.agents
      where tenant_id = p_tenant_id and role = v_row->>'role'
    );
  end loop;
end;
$$;

revoke all on function public.materialize_builtin_agents(uuid) from public;
grant execute on function public.materialize_builtin_agents(uuid) to service_role;

-- Backfill the security agent for existing tenants. Idempotent.
do $$
declare
  t record;
begin
  for t in select id from public.tenants loop
    perform public.materialize_builtin_agents(t.id);
  end loop;
end;
$$;

commit;
